const bcrypt = require('bcryptjs');

// Gerando o hash uma única vez para performance
const hashPadrao = bcrypt.hashSync('123456', 8);

const users = [
  { username: 'Lucas', password: hashPadrao, favorecidos: ['Maria', 'jack'], saldo: 5000 },
  { username: 'Maria', password: hashPadrao, favorecidos: ['jack', 'ana_silva'], saldo: 3000 },
  { username: 'jack', password: hashPadrao, favorecidos: ['Lucas', 'pedro_h'], saldo: 3000 },
  { username: 'ana_silva', password: hashPadrao, favorecidos: ['Lucas'], saldo: 1500 },
  { username: 'pedro_h', password: hashPadrao, favorecidos: ['Maria', 'julia_lopes'], saldo: 4200 },
  { username: 'julia_lopes', password: hashPadrao, favorecidos: ['carlos_edu'], saldo: 1850 },
  { username: 'carlos_edu', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 12000 },
  { username: 'beatriz_m', password: hashPadrao, favorecidos: ['rodrigo_f'], saldo: 2700 },
  { username: 'rodrigo_f', password: hashPadrao, favorecidos: ['pedro_h'], saldo: 3100 },
  { username: 'fernanda_o', password: hashPadrao, favorecidos: ['Maria'], saldo: 6700 },
  { username: 'gabriel_s', password: hashPadrao, favorecidos: ['larissa_v'], saldo: 1900 },
  { username: 'larissa_v', password: hashPadrao, favorecidos: ['beatriz_m'], saldo: 4500 },
  { username: 'rafael_c', password: hashPadrao, favorecidos: ['amanda_r'], saldo: 5200 },
  { username: 'amanda_r', password: hashPadrao, favorecidos: ['Lucas'], saldo: 3300 },
  { username: 'bruno_t', password: hashPadrao, favorecidos: ['camila_g'], saldo: 1100 },
  { username: 'camila_g', password: hashPadrao, favorecidos: ['jack'], saldo: 8900 },
  { username: 'diego_m', password: hashPadrao, favorecidos: ['isabela_p'], saldo: 2150 },
  { username: 'isabela_p', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 4000 },
  { username: 'thiago_a', password: hashPadrao, favorecidos: ['vanessa_f'], saldo: 1300 },
  { username: 'vanessa_f', password: hashPadrao, favorecidos: ['fernanda_o'], saldo: 7200 },
  { username: 'marcos_j', password: hashPadrao, favorecidos: ['aline_d'], saldo: 1550 },
  { username: 'aline_d', password: hashPadrao, favorecidos: ['pedro_h'], saldo: 6200 },
  { username: 'vitor_s', password: hashPadrao, favorecidos: ['leticia_k'], saldo: 3400 },
  { username: 'leticia_k', password: hashPadrao, favorecidos: ['Maria'], saldo: 1800 },
  { username: 'ricardo_u', password: hashPadrao, favorecidos: ['patricia_l'], saldo: 9500 },
  { username: 'patricia_l', password: hashPadrao, favorecidos: ['Lucas'], saldo: 2600 },
  { username: 'felipe_q', password: hashPadrao, favorecidos: ['renata_n'], saldo: 4100 },
  { username: 'renata_n', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 5800 },
  { username: 'gustavo_b', password: hashPadrao, favorecidos: ['daniela_y'], saldo: 1250 },
  { username: 'daniela_y', password: hashPadrao, favorecidos: ['jack'], saldo: 7600 },
  { username: 'andre_w', password: hashPadrao, favorecidos: ['juliana_x'], saldo: 3200 },
  { username: 'juliana_x', password: hashPadrao, favorecidos: ['Maria'], saldo: 2900 },
  { username: 'leonardo_z', password: hashPadrao, favorecidos: ['monica_e'], saldo: 8400 },
  { username: 'monica_e', password: hashPadrao, favorecidos: ['Lucas'], saldo: 1700 },
  { username: 'caio_r', password: hashPadrao, favorecidos: ['sabrina_v'], saldo: 6300 },
  { username: 'sabrina_v', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 4400 },
  { username: 'hugo_m', password: hashPadrao, favorecidos: ['lorena_t'], saldo: 11000 },
  { username: 'lorena_t', password: hashPadrao, favorecidos: ['beatriz_m'], saldo: 3700 },
  { username: 'igor_s', password: hashPadrao, favorecidos: ['bianca_c'], saldo: 5100 },
  { username: 'bianca_c', password: hashPadrao, favorecidos: ['Maria'], saldo: 2300 },
  { username: 'murilo_p', password: hashPadrao, favorecidos: ['priscila_o'], saldo: 1900 },
  { username: 'priscila_o', password: hashPadrao, favorecidos: ['jack'], saldo: 6800 },
  { username: 'samuel_f', password: hashPadrao, favorecidos: ['tatiane_g'], saldo: 3500 },
  { username: 'tatiane_g', password: hashPadrao, favorecidos: ['Lucas'], saldo: 5900 },
  { username: 'vinicius_h', password: hashPadrao, favorecidos: ['debora_a'], saldo: 1400 },
  { username: 'debora_a', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 8200 },
  { username: 'arthur_k', password: hashPadrao, favorecidos: ['natalia_j'], saldo: 4700 },
  { username: 'natalia_j', password: hashPadrao, favorecidos: ['Maria'], saldo: 3100 },
  { username: 'douglas_l', password: hashPadrao, favorecidos: ['elaine_s'], saldo: 2200 },
  { username: 'elaine_s', password: hashPadrao, favorecidos: ['jack'], saldo: 7500 },
  { username: 'eduardo_v', password: hashPadrao, favorecidos: ['fabiana_m'], saldo: 1100 },
  { username: 'fabiana_m', password: hashPadrao, favorecidos: ['Lucas'], saldo: 5300 },
  { username: 'giovanni_p', password: hashPadrao, favorecidos: ['helena_r'], saldo: 4800 },
  { username: 'helena_r', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 9600 },
  { username: 'itamar_c', password: hashPadrao, favorecidos: ['jessica_t'], saldo: 1600 },
  { username: 'jessica_t', password: hashPadrao, favorecidos: ['Maria'], saldo: 3900 },
  { username: 'kleber_s', password: hashPadrao, favorecidos: ['lidia_o'], saldo: 2800 },
  { username: 'lidia_o', password: hashPadrao, favorecidos: ['jack'], saldo: 6100 },
  { username: 'maicon_z', password: hashPadrao, favorecidos: ['naiara_q'], saldo: 4400 },
  { username: 'naiara_q', password: hashPadrao, favorecidos: ['Lucas'], saldo: 7700 },
  { username: 'otavio_b', password: hashPadrao, favorecidos: ['paula_d'], saldo: 1350 },
  { username: 'paula_d', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 5400 },
  { username: 'quelvin_x', password: hashPadrao, favorecidos: ['roberta_p'], saldo: 3200 },
  { username: 'roberta_p', password: hashPadrao, favorecidos: ['Maria'], saldo: 8800 },
  { username: 'sergio_f', password: hashPadrao, favorecidos: ['talita_u'], saldo: 2400 },
  { username: 'talita_u', password: hashPadrao, favorecidos: ['jack'], saldo: 4100 },
  { username: 'ubiratan_g', password: hashPadrao, favorecidos: ['valeria_h'], saldo: 1900 },
  { username: 'valeria_h', password: hashPadrao, favorecidos: ['Lucas'], saldo: 6500 },
  { username: 'wagner_l', password: hashPadrao, favorecidos: ['yasmin_v'], saldo: 2000 },
  { username: 'yasmin_v', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 7100 },
  { username: 'zeferino_s', password: hashPadrao, favorecidos: ['antonio_p'], saldo: 1100 },
  { username: 'antonio_p', password: hashPadrao, favorecidos: ['Maria'], saldo: 5600 },
  { username: 'barbara_m', password: hashPadrao, favorecidos: ['claudio_r'], saldo: 3800 },
  { username: 'claudio_r', password: hashPadrao, favorecidos: ['jack'], saldo: 8200 },
  { username: 'daiane_f', password: hashPadrao, favorecidos: ['emerson_t'], saldo: 2900 },
  { username: 'emerson_t', password: hashPadrao, favorecidos: ['Lucas'], saldo: 4700 },
  { username: 'flavia_b', password: hashPadrao, favorecidos: ['gilberto_o'], saldo: 1500 },
  { username: 'gilberto_o', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 9300 },
  { username: 'heloisa_c', password: hashPadrao, favorecidos: ['israel_k'], saldo: 3400 },
  { username: 'israel_k', password: hashPadrao, favorecidos: ['Maria'], saldo: 6000 },
  { username: 'jair_z', password: hashPadrao, favorecidos: ['katia_v'], saldo: 2100 },
  { username: 'katia_v', password: hashPadrao, favorecidos: ['jack'], saldo: 7400 },
  { username: 'laercio_m', password: hashPadrao, favorecidos: ['marlene_q'], saldo: 4300 },
  { username: 'marlene_q', password: hashPadrao, favorecidos: ['Lucas'], saldo: 8600 },
  { username: 'nilson_h', password: hashPadrao, favorecidos: ['olivia_d'], saldo: 1200 },
  { username: 'olivia_d', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 5200 },
  { username: 'pablo_u', password: hashPadrao, favorecidos: ['quezia_s'], saldo: 3100 },
  { username: 'quezia_s', password: hashPadrao, favorecidos: ['Maria'], saldo: 6900 },
  { username: 'ronaldo_x', password: hashPadrao, favorecidos: ['simone_a'], saldo: 2500 },
  { username: 'simone_a', password: hashPadrao, favorecidos: ['jack'], saldo: 7800 },
  { username: 'tarcisio_p', password: hashPadrao, favorecidos: ['ursula_g'], saldo: 4000 },
  { username: 'ursula_g', password: hashPadrao, favorecidos: ['Lucas'], saldo: 9100 },
  { username: 'valter_f', password: hashPadrao, favorecidos: ['waldir_k'], saldo: 1800 },
  { username: 'waldir_k', password: hashPadrao, favorecidos: ['ana_silva'], saldo: 6300 },
  { username: 'xavier_r', password: hashPadrao, favorecidos: ['yuri_b'], saldo: 2200 },
  { username: 'yuri_b', password: hashPadrao, favorecidos: ['Maria'], saldo: 5700 },
  { username: 'zenilda_o', password: hashPadrao, favorecidos: ['anderson_p'], saldo: 3500 },
  { username: 'anderson_p', password: hashPadrao, favorecidos: ['jack'], saldo: 8100 },
  { username: 'brenda_l', password: hashPadrao, favorecidos: ['cristiano_v'], saldo: 1400 },
  { username: 'cristiano_v', password: hashPadrao, favorecidos: ['Lucas'], saldo: 9900 }
];

module.exports = users;